"""Initial migration

Revision ID: 0bd1de1a4627
Revises: 
Create Date: 2024-12-21 17:40:21.030012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd1de1a4627'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_test',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('test_name', sa.String(length=100), nullable=False),
    sa.Column('test_description', sa.Text(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('result_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_record.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_record.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription_record',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('doctor_name', sa.String(), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('medicine_1_name', sa.String(), nullable=True),
    sa.Column('medicine_1_dosage_description', sa.String(), nullable=True),
    sa.Column('medicine_2_name', sa.String(), nullable=True),
    sa.Column('medicine_2_dosage_description', sa.String(), nullable=True),
    sa.Column('medicine_3_name', sa.String(), nullable=True),
    sa.Column('medicine_3_dosage_description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_record.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_record.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charges', sa.Float(), nullable=True))
        batch_op.drop_constraint('appointment_record_id_key', type_='unique')

    with op.batch_alter_table('patient_record', schema=None) as batch_op:
        batch_op.drop_constraint('patient_record_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_record', schema=None) as batch_op:
        batch_op.create_unique_constraint('patient_record_id_key', ['id'])

    with op.batch_alter_table('appointment_record', schema=None) as batch_op:
        batch_op.create_unique_constraint('appointment_record_id_key', ['id'])
        batch_op.drop_column('charges')

    op.drop_table('prescription_record')
    op.drop_table('medical_test')
    # ### end Alembic commands ###
