"""Initial migration with departments and relationships

Revision ID: 38ce625d5efd
Revises: 
Create Date: 2024-12-16 18:54:07.432737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ce625d5efd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_test',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('test_name', sa.String(length=100), nullable=False),
    sa.Column('test_description', sa.Text(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('result_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_record.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_record.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('doctor_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'Pending'::text"))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint('appointment_record_doctor_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('appointment_record_patient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'patient_record', ['patient_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'doctor_record', ['doctor_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'doctor_record', ['head_doctor_id'], ['id'])

    with op.batch_alter_table('doctor_record', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('blood_group',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5),
               nullable=False)
        batch_op.alter_column('department_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('department_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('contact_number_1',
               existing_type=sa.TEXT(),
               type_=sa.String(length=15),
               nullable=False)
        batch_op.alter_column('contact_number_2',
               existing_type=sa.TEXT(),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('aadhar_or_voter_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('email_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('qualification',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('specialisation',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('years_of_experience',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('pin_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.drop_index('idx_16391_sqlite_autoindex_doctor_record_2')
        batch_op.drop_index('idx_16391_sqlite_autoindex_doctor_record_3')
        batch_op.create_unique_constraint(None, ['email_id'])

    with op.batch_alter_table('patient_record', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('contact_number_1',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('contact_number_2',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('email_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('next_of_kin_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('next_of_kin_relation_to_patient',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('next_of_kin_contact_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('qr_code_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.drop_index('idx_16386_sqlite_autoindex_patient_record_2')
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('aadhar_or_voter_id')
        batch_op.drop_column('time_of_registration')
        batch_op.drop_column('city')
        batch_op.drop_column('date_of_registration')
        batch_op.drop_column('pin_code')
        batch_op.drop_column('height')
        batch_op.drop_column('state')
        batch_op.drop_column('weight')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('blood_group')

    with op.batch_alter_table('prescription_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('patient_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('doctor_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('doctor_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('diagnosis',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('comments',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('medicine_1_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('medicine_1_dosage_description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('medicine_2_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('medicine_2_dosage_description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('medicine_3_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('medicine_3_dosage_description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prescription_record', schema=None) as batch_op:
        batch_op.alter_column('medicine_3_dosage_description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('medicine_3_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('medicine_2_dosage_description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('medicine_2_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('medicine_1_dosage_description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('medicine_1_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('comments',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('diagnosis',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('doctor_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('doctor_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('patient_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('patient_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_group', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('weight', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('height', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pin_code', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_of_registration', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('time_of_registration', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('aadhar_or_voter_id', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('idx_16386_sqlite_autoindex_patient_record_2', ['aadhar_or_voter_id'], unique=True)
        batch_op.alter_column('qr_code_path',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('next_of_kin_contact_number',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('next_of_kin_relation_to_patient',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('next_of_kin_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('contact_number_2',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('contact_number_1',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('doctor_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('idx_16391_sqlite_autoindex_doctor_record_3', ['email_id'], unique=True)
        batch_op.create_index('idx_16391_sqlite_autoindex_doctor_record_2', ['aadhar_or_voter_id'], unique=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('pin_code',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('years_of_experience',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('specialisation',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('qualification',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('email_id',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('aadhar_or_voter_id',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('contact_number_2',
               existing_type=sa.String(length=15),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('contact_number_1',
               existing_type=sa.String(length=15),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('department_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('blood_group',
               existing_type=sa.String(length=5),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('appointment_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('appointment_record_patient_id_fkey', 'patient_record', ['patient_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('appointment_record_doctor_id_fkey', 'doctor_record', ['doctor_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'Pending'::text"))
        batch_op.alter_column('reason',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('doctor_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('patient_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('notes')

    op.drop_table('medical_test')
    # ### end Alembic commands ###
